spring:
  datasource:
#    url: jdbc:mysql://82.156.18.228:3306/brainwave?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#    password: kd2#*a*71p&*jiam&*
    url: jdbc:mysql://150.158.16.219:3306/brainwave?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    password: 420426539
    username: root
  redis:
    database: 3
    password: 7#ac!189kio&1
#    host: 82.156.18.228
    host: 150.158.16.219
    port: 6379
    lettuce:
      pool:
        max-active: 50
        max-wait: 10
        max-idle: 20
    timeout: 5000
    connect-timeout: 5000

mybatis-plus:
  configuration:
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #在该仓储包下的类省略全类名
  type-aliases-package: com.chat.infrastructure.po
  mapper-locations: classpath:/mapper/*.xml

#forest:
#  variables:
#    test:
knife4j:
  enable: true
openai:
  chat:
    key: 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
    host: https://api.openai-proxy.com

wechat:
  appid: xxx
  secret: xxx



